spring:
  application:
    name: card-service
  data:
    mongodb:
      uri: mongodb+srv://bankAdmin:grupo4ntt@bootcamp-bank.2c7fx6u.mongodb.net/bootcamp-bank?retryWrites=true&w=majority&appName=bootcamp-bank
      database: cardDB

server:
  port: 8085

eureka:
  client:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      customer-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.lang.Exception
      transaction-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.lang.Exception

  timelimiter:
    instances:
      customer-service:
        timeoutDuration: 2s
        cancelRunningFuture: true
      transaction-service:
        timeoutDuration: 2s
        cancelRunningFuture: true
